- name: Create Folder HealthCheck
  become: true
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  #    owner: "{{ ansible_user }}"
  with_items:
    - "{{local_path}}/healthcheck"

- name: Create HealthCheck container
  containers.podman.podman_container:
    name: healthcheck
    image: dwh-ap-southeast-3.cr.bytepluses.com/dw-app/healthchecks:4.1.1
    state: started
    restart_policy: unless-stopped
    interactive: true
    tty: true
    recreate: true
    env:
        DB: "postgres"
        DB_CONN_MAX_AGE: "0"
        DB_HOST: "{{host_dwh_staging_pg}}"
        DB_NAME: healthcheck
        DB_PASSWORD: "confidential"
        DB_PORT: "2{{citus_port}}"
        DB_SSLMODE: prefer
        DB_TARGET_SESSION_ATTRS: read-write
        DB_USER: dwh
        DEBUG: "False"
        DEFAULT_FROM_EMAIL: "admin.dwh@jiarsi.com"
        EMAIL_HOST: "smtp.google.com"
        EMAIL_HOST_PASSWORD: ""
        EMAIL_HOST_USER: "admin.dwh@jiarsi.com"
        EMAIL_PORT: 587
        EMAIL_USE_TLS: True
        SECRET_KEY: "TralalaTrololo"
        SITE_ROOT: http://localhost:8000
    volumes:
      - "{{local_path}}/healthcheck:/data:z"
    ports:
      - "6667:8000"
    network:
      - apjn
    shm_size: "1gb"
