- name: postgres Environment
  hosts: database_ods_clickhouse
  become: true
  gather_facts: true
  become_user: "{{ ansible_user }}"
  vars:
    pod_name: 'clickhouse'
  tasks:
    - name: --Initialize-- Certificate
      ansible.builtin.include_tasks: "stack/clickhouse/postgres.yml"

